apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: agbora
    namespace: argocd
spec:
    generators:
    - git:
        directories:
        - path: prod/*
        repoURL: https://github.com/blancoramiro/testrepo
        revision: HEAD
    template:
      metadata:
        name: '{{path.basename}}'
        namespace: default
      spec:
        destination:
          namespace: default
          server: https://kubernetes.default.svc
        project: default
        source:
          directory:
            recurse: true
          path: '{{path}}'
          repoURL: https://github.com/blancoramiro/testrepo
          targetRevision: HEAD
        syncPolicy:
          #automated: {}
            #prune: true
          syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true
