apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-app-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-github-app-k8s
    creationPolicy: Owner
  dataFrom:
  - extract:
      conversionStrategy: Default
      key: "ARGOCD_GITHUB_APP"
