apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- application_set.yaml  
helmGlobals:
  chartHome: ../../charts
helmCharts:
- name: argo-cd-7.7.0
  releaseName: argocd
  namespace: argocd
  valuesFile: values.yaml
  includeCRDs: true
