apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
helmGlobals:
  chartHome: ../../charts
resources:
- argocd-github-app-secret.yaml
helmCharts:
- name: argo-cd-7.7.0
  releaseName: argocd
  namespace: argocd
  valuesFile: values.yaml
  includeCRDs: true
